variable "default_interpreter" {
  default = ["/usr/bin/env", "bash", "-c"]
}

variable "extensions" {
  description = "Extensions that will be added to the VSCode installation."
  default = [
    "4ops.terraform",
    "alanwalk.markdown-toc",
    "bungcip.better-toml",
    "bierner.markdown-mermaid",
    "burtlo.inspec",
    "Compulim.indent4to2",
    "coolbear.systemd-unit-file",
    "DavidAnson.vscode-markdownlint",
    "eamodio.gitlens",
    "apollographql.vscode-apollo",
    "dbaeumer.vscode-eslint",
    "deerawan.vscode-dash",
    "eamodio.gitlens",
    "EditorConfig.EditorConfig",
    "esbenp.prettier-vscode",
    "flowtype.flow-for-vscode",
    "formulahendry.docker-explorer",
    "formulahendry.docker-extension-pack",
    "frankschmid.serverless-vscode",
    "gerane.Theme-Monokai",
    "gitduck.code-streaming",
    "GitLab.gitlab-workflow",
    "golang.go",
    "hashicorp.terraform",
    "KnisterPeter.vscode-commitizen",
    "lextudio.restructuredtext",
    "mechatroner.rainbow-csv",
    "mgmcdermott.vscode-language-babel",
    "mhutchie.git-graph",
    "henriiik.docker-linter",
    "marcostazi.VS-code-vagrantfile",
    "maximetinu.identical-sublime-monokai-csharp-theme-colorizer",
    "mikestead.dotenv",
    "ms-python.python",
    "ms-vscode.cpptools",
    "ms-vscode.sublime-keybindings",
    "rebornix.ruby",
    "redhat.vscode-yaml",
    "streetsidesoftware.code-spell-checker",
    "timonwong.shellcheck",
    "Tyriar.sort-lines",
    "wholroyd.HCL",
    "ms-toolsai.jupyter",
    "ms-vscode-remote.remote-containers",
    "ms-vscode-remote.remote-ssh",
    "ms-vscode-remote.remote-ssh-edit",
    "ms-vscode-remote.remote-ssh-edit-nightly",
    "ms-vscode-remote.remote-wsl",
    "ms-vscode-remote.vscode-remote-extensionpack",
    "ms-vsliveshare.vsliveshare",
    "msjsdiag.debugger-for-chrome",
    "p1c2u.docker-compose",
    "RandomFractalsInc.geo-data-viewer",
    "shd101wyy.markdown-preview-enhanced",
    "waderyan.gitblame",
    "yzhang.markdown-all-in-one",
    "zamerick.vscode-caddyfile-syntax",
  ]
}